FROM            eb-docker:base
MAINTAINER      d.sehyeon@gmail.com

ENV             BUILD_MODE      local

ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            .   /srv/project
